title: SupGeekRod's DevBlog

keywords: ""
description: "SupGeekRod's development experience and insights"
baseurl: "/"    # the subpath of your site, e.g. /blog
url: ""         # the base hostname & protocol for your site, e.g. http://example.com

author: supgeek-rod
email: your-email@example.com

github_username: supgeek-rod
