remote_theme: supgeek-rod/jekyll-theme-github-like@e8df58099cd942777a21bc9199a9242133820612
plugins:
  - jekyll-remote-theme

title: SupeRod's DevBlog
description: "SupeRod's development experience and insights"

author: supgeek-rod
email: supgeek.rod@gmail.com
